### ISSUE TITLE
intelude.h missing

### ISSUE THREAD

**Issue by giladrefael** [cogsys-tuebingen/csapex_generic_obstacle_detection#1]
After following the csapex project installation instructions, I cloned the csapex_generic_obstacle_detection to the csapex plugins folder but I got a compilation error 

`
/home/user/ws/csapex/src/csapex/plugins/csapex_core_plugins/csapex_generic_obstacle_detection/src/obstacle_detection/obstacle_detector.cpp:17:42: fatal error: csapex/profiling/interlude.hpp: No such file or directory`

**Comment by betwo** [comment]
Thanks for the report. I pushed the missing commits

**Comment by giladrefael** [comment]
Problem solved, thank you!
